# GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug_x32
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild prelink

ifeq ($(config),debug_x32)
  RESCOMP = windres
  TARGETDIR = ../../../../bin/Debug-linux-x86_64
  TARGET = $(TARGETDIR)/sandbox_x86_d
  OBJDIR = ../../../../bin-int/Debug-linux-x86_64/x32/Debug/sandbox
  DEFINES += -DLD_PATH=\"/home/qrikko/Documents/development/open.git/plugins/Debug-linux-x86_64//Debug-linux-x86_64\" -DDEBUG
  INCLUDES += -I../../../core/src -I../.. -I../../cglm/include -I../../vulkan-headers/include -I../../log.c/src -I../../dmt/src
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -g -std=gnu99 -msse4.1 -fPIC
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -g -fno-exceptions -fno-rtti -msse4.1 -fPIC
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += ../../../../lib/Debug-linux-x86_64/libopen_x86_d.a -lm -ldl
  LDDEPS += ../../../../lib/Debug-linux-x86_64/libopen_x86_d.a
  ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -L../../../../bin/Debug-linux-x86_64 -Wl,-rpath=/home/qrikko/Documents/development/open.git/plugins/Debug-linux-x86_64/
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),debug_x64)
  RESCOMP = windres
  TARGETDIR = ../../../../bin/Debug-linux-x86_64
  TARGET = $(TARGETDIR)/sandbox_x64_d
  OBJDIR = ../../../../bin-int/Debug-linux-x86_64/x64/Debug/sandbox
  DEFINES += -DLD_PATH=\"/home/qrikko/Documents/development/open.git/plugins/Debug-linux-x86_64//Debug-linux-x86_64\" -DDEBUG
  INCLUDES += -I../../../core/src -I../.. -I../../cglm/include -I../../vulkan-headers/include -I../../log.c/src -I../../dmt/src
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -g -std=gnu99 -msse4.1 -fPIC
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -g -fno-exceptions -fno-rtti -msse4.1 -fPIC
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += ../../../../lib/Debug-linux-x86_64/libopen_x64_d.a -lm -ldl
  LDDEPS += ../../../../lib/Debug-linux-x86_64/libopen_x64_d.a
  ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -L../../../../bin/Debug-linux-x86_64 -Wl,-rpath=/home/qrikko/Documents/development/open.git/plugins/Debug-linux-x86_64/
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),release_x32)
  RESCOMP = windres
  TARGETDIR = ../../../../bin/Release-linux-x86_64
  TARGET = $(TARGETDIR)/sandbox_x86
  OBJDIR = ../../../../bin-int/Release-linux-x86_64/x32/Release/sandbox
  DEFINES += -DNDEBUG -DLD_PATH=\"/home/qrikko/Documents/development/open.git/plugins/Release-linux-x86_64//Release-linux-x86_64\" -DRELEASE
  INCLUDES += -I../../../core/src -I../.. -I../../cglm/include -I../../vulkan-headers/include -I../../log.c/src
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -msse2 -std=gnu99 -msse4.1 -fPIC
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -msse2 -fno-exceptions -fno-rtti -msse4.1 -fPIC
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += ../../../../lib/Release-linux-x86_64/libopen_x86.a -lm -ldl
  LDDEPS += ../../../../lib/Release-linux-x86_64/libopen_x86.a
  ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -s -L../../../../bin/Release-linux-x86_64 -Wl,-rpath=/home/qrikko/Documents/development/open.git/plugins/Release-linux-x86_64/
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),release_x64)
  RESCOMP = windres
  TARGETDIR = ../../../../bin/Release-linux-x86_64
  TARGET = $(TARGETDIR)/sandbox_x64
  OBJDIR = ../../../../bin-int/Release-linux-x86_64/x64/Release/sandbox
  DEFINES += -DNDEBUG -DLD_PATH=\"/home/qrikko/Documents/development/open.git/plugins/Release-linux-x86_64//Release-linux-x86_64\" -DRELEASE
  INCLUDES += -I../../../core/src -I../.. -I../../cglm/include -I../../vulkan-headers/include -I../../log.c/src
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -std=gnu99 -msse4.1 -fPIC
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -fno-exceptions -fno-rtti -msse4.1 -fPIC
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += ../../../../lib/Release-linux-x86_64/libopen_x64.a -lm -ldl
  LDDEPS += ../../../../lib/Release-linux-x86_64/libopen_x64.a
  ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -s -L../../../../bin/Release-linux-x86_64 -Wl,-rpath=/home/qrikko/Documents/development/open.git/plugins/Release-linux-x86_64/
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

OBJECTS := \
	$(OBJDIR)/sandbox.o \

RESOURCES := \

CUSTOMFILES := \

SHELLTYPE := posix
ifeq (.exe,$(findstring .exe,$(ComSpec)))
	SHELLTYPE := msdos
endif

$(TARGET): $(GCH) ${CUSTOMFILES} $(OBJECTS) $(LDDEPS) $(RESOURCES) | $(TARGETDIR)
	@echo Linking sandbox
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(CUSTOMFILES): | $(OBJDIR)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning sandbox
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) $(PCH) | $(OBJDIR)
$(GCH): $(PCH) | $(OBJDIR)
	@echo $(notdir $<)
	$(SILENT) $(CC) -x c-header $(ALL_CFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
else
$(OBJECTS): | $(OBJDIR)
endif

$(OBJDIR)/sandbox.o: ../../../frontend/sandbox/sandbox.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(OBJDIR)/$(notdir $(PCH)).d
endif