# GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug_x32
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild prelink

ifeq ($(config),debug_x32)
  RESCOMP = windres
  TARGETDIR = ../../../../plugins/Debug-linux-x86_64
  TARGET = $(TARGETDIR)/libvulkan_api_module_x86_d.so
  OBJDIR = ../../../../bin-int/Debug-linux-x86_64/x32/Debug/vulkan_api_module
  DEFINES += -DLD_PATH=\"/home/qrikko/Documents/development/open.git/plugins/Debug-linux-x86_64//Debug-linux-x86_64\" -DDEBUG -DMODULE
  INCLUDES += -I../../../core/src -I../.. -I../../log.c/src -I../../cglm/include -I../../stb -I../../imgui -I../../vulkan-headers/include -I../../dmt/src
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC -g -std=gnu99 -msse4.1 -fPIC
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC -g -fno-exceptions -fno-rtti -msse4.1 -fPIC
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += ../../../../lib/Debug-linux-x86_64/libopen_x86_d.a -lcglm -lvulkan
  LDDEPS += ../../../../lib/Debug-linux-x86_64/libopen_x86_d.a
  ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -shared -Wl,-soname=libvulkan_api_module_x86_d.so -L../../../../plugins/Debug-linux-x86_64 -Wl,-rpath=/home/qrikko/Documents/development/open.git/plugins/Debug-linux-x86_64/
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),debug_x64)
  RESCOMP = windres
  TARGETDIR = ../../../../plugins/Debug-linux-x86_64
  TARGET = $(TARGETDIR)/libvulkan_api_module_x64_d.so
  OBJDIR = ../../../../bin-int/Debug-linux-x86_64/x64/Debug/vulkan_api_module
  DEFINES += -DLD_PATH=\"/home/qrikko/Documents/development/open.git/plugins/Debug-linux-x86_64//Debug-linux-x86_64\" -DDEBUG -DMODULE
  INCLUDES += -I../../../core/src -I../.. -I../../log.c/src -I../../cglm/include -I../../stb -I../../imgui -I../../vulkan-headers/include -I../../dmt/src
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC -g -std=gnu99 -msse4.1 -fPIC
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -fPIC -g -fno-exceptions -fno-rtti -msse4.1 -fPIC
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += ../../../../lib/Debug-linux-x86_64/libopen_x64_d.a -lcglm -lvulkan
  LDDEPS += ../../../../lib/Debug-linux-x86_64/libopen_x64_d.a
  ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -shared -Wl,-soname=libvulkan_api_module_x64_d.so -L../../../../plugins/Debug-linux-x86_64 -Wl,-rpath=/home/qrikko/Documents/development/open.git/plugins/Debug-linux-x86_64/
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),release_x32)
  RESCOMP = windres
  TARGETDIR = ../../../../plugins/Release-linux-x86_64
  TARGET = $(TARGETDIR)/libvulkan_api_module_x86.so
  OBJDIR = ../../../../bin-int/Release-linux-x86_64/x32/Release/vulkan_api_module
  DEFINES += -DNDEBUG -DLD_PATH=\"/home/qrikko/Documents/development/open.git/plugins/Release-linux-x86_64//Release-linux-x86_64\" -DRELEASE -DMODULE
  INCLUDES += -I../../../core/src -I../.. -I../../log.c/src -I../../cglm/include -I../../stb -I../../imgui -I../../vulkan-headers/include
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -fPIC -g -msse2 -std=gnu99 -msse4.1 -fPIC
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -fPIC -g -msse2 -fno-exceptions -fno-rtti -msse4.1 -fPIC
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += ../../../../lib/Release-linux-x86_64/libopen_x86.a -lcglm -lvulkan
  LDDEPS += ../../../../lib/Release-linux-x86_64/libopen_x86.a
  ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -shared -Wl,-soname=libvulkan_api_module_x86.so -L../../../../plugins/Release-linux-x86_64 -Wl,-rpath=/home/qrikko/Documents/development/open.git/plugins/Release-linux-x86_64/
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),release_x64)
  RESCOMP = windres
  TARGETDIR = ../../../../plugins/Release-linux-x86_64
  TARGET = $(TARGETDIR)/libvulkan_api_module_x64.so
  OBJDIR = ../../../../bin-int/Release-linux-x86_64/x64/Release/vulkan_api_module
  DEFINES += -DNDEBUG -DLD_PATH=\"/home/qrikko/Documents/development/open.git/plugins/Release-linux-x86_64//Release-linux-x86_64\" -DRELEASE -DMODULE
  INCLUDES += -I../../../core/src -I../.. -I../../log.c/src -I../../cglm/include -I../../stb -I../../imgui -I../../vulkan-headers/include
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -fPIC -g -std=gnu99 -msse4.1 -fPIC
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -fPIC -g -fno-exceptions -fno-rtti -msse4.1 -fPIC
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += ../../../../lib/Release-linux-x86_64/libopen_x64.a -lcglm -lvulkan
  LDDEPS += ../../../../lib/Release-linux-x86_64/libopen_x64.a
  ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -shared -Wl,-soname=libvulkan_api_module_x64.so -L../../../../plugins/Release-linux-x86_64 -Wl,-rpath=/home/qrikko/Documents/development/open.git/plugins/Release-linux-x86_64/
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

OBJECTS := \
	$(OBJDIR)/vulkan_api_module.o \
	$(OBJDIR)/vulkan_command_buffers.o \
	$(OBJDIR)/vulkan_command_pool.o \
	$(OBJDIR)/vulkan_dynamic_pipeline.o \
	$(OBJDIR)/vulkan_framebuffer.o \
	$(OBJDIR)/vulkan_graphics_pipeline.o \
	$(OBJDIR)/vulkan_image_views.o \
	$(OBJDIR)/vulkan_instance.o \
	$(OBJDIR)/vulkan_logical_device.o \
	$(OBJDIR)/vulkan_physical_device.o \
	$(OBJDIR)/vulkan_queue_families.o \
	$(OBJDIR)/vulkan_render_pass.o \
	$(OBJDIR)/vulkan_surface.o \
	$(OBJDIR)/vulkan_swapchain.o \
	$(OBJDIR)/vulkan_sync_objects.o \
	$(OBJDIR)/vulkan_texture2d.o \
	$(OBJDIR)/vulkan_uniform_buffer.o \
	$(OBJDIR)/vulkan_validation_layers.o \
	$(OBJDIR)/vulkan_vertex_buffer.o \
	$(OBJDIR)/vulkan_vertex_description.o \

RESOURCES := \

CUSTOMFILES := \

SHELLTYPE := posix
ifeq (.exe,$(findstring .exe,$(ComSpec)))
	SHELLTYPE := msdos
endif

$(TARGET): $(GCH) ${CUSTOMFILES} $(OBJECTS) $(LDDEPS) $(RESOURCES) | $(TARGETDIR)
	@echo Linking vulkan_api_module
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(CUSTOMFILES): | $(OBJDIR)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning vulkan_api_module
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) $(PCH) | $(OBJDIR)
$(GCH): $(PCH) | $(OBJDIR)
	@echo $(notdir $<)
	$(SILENT) $(CC) -x c-header $(ALL_CFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
else
$(OBJECTS): | $(OBJDIR)
endif

$(OBJDIR)/vulkan_api_module.o: ../../../modules/vulkan_api_module/vulkan_api_module.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/vulkan_command_buffers.o: ../../../modules/vulkan_api_module/vulkan_command_buffers.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/vulkan_command_pool.o: ../../../modules/vulkan_api_module/vulkan_command_pool.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/vulkan_dynamic_pipeline.o: ../../../modules/vulkan_api_module/vulkan_dynamic_pipeline.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/vulkan_framebuffer.o: ../../../modules/vulkan_api_module/vulkan_framebuffer.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/vulkan_graphics_pipeline.o: ../../../modules/vulkan_api_module/vulkan_graphics_pipeline.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/vulkan_image_views.o: ../../../modules/vulkan_api_module/vulkan_image_views.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/vulkan_instance.o: ../../../modules/vulkan_api_module/vulkan_instance.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/vulkan_logical_device.o: ../../../modules/vulkan_api_module/vulkan_logical_device.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/vulkan_physical_device.o: ../../../modules/vulkan_api_module/vulkan_physical_device.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/vulkan_queue_families.o: ../../../modules/vulkan_api_module/vulkan_queue_families.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/vulkan_render_pass.o: ../../../modules/vulkan_api_module/vulkan_render_pass.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/vulkan_surface.o: ../../../modules/vulkan_api_module/vulkan_surface.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/vulkan_swapchain.o: ../../../modules/vulkan_api_module/vulkan_swapchain.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/vulkan_sync_objects.o: ../../../modules/vulkan_api_module/vulkan_sync_objects.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/vulkan_texture2d.o: ../../../modules/vulkan_api_module/vulkan_texture2d.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/vulkan_uniform_buffer.o: ../../../modules/vulkan_api_module/vulkan_uniform_buffer.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/vulkan_validation_layers.o: ../../../modules/vulkan_api_module/vulkan_validation_layers.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/vulkan_vertex_buffer.o: ../../../modules/vulkan_api_module/vulkan_vertex_buffer.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/vulkan_vertex_description.o: ../../../modules/vulkan_api_module/vulkan_vertex_description.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(OBJDIR)/$(notdir $(PCH)).d
endif